# Generated by Django 4.1.5 on 2024-01-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acApp', '0003_user_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
